"""harden oauth states

Revision ID: e4e587eda094
Revises: fcaf17d3b49b
Create Date: 2026-08-19 21:22:42.533847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e587eda094'
down_revision: Union[str, Sequence[str], None] = 'fcaf17d3b49b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=32), server_default='facebook', nullable=False))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_oauth_states_provider'), ['provider'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_states_provider'))
        batch_op.drop_column('consumed_at')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
