"""add provider neutral scheduled targets

Revision ID: e6a396f1c707
Revises: e4e587eda094
Create Date: 2026-08-19 21:43:54.439489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a396f1c707'
down_revision: Union[str, Sequence[str], None] = 'e4e587eda094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posting_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_account_id', sa.Integer(), nullable=True))
        batch_op.alter_column('meta_page_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_posting_preferences_linkedin_account_id'), ['linkedin_account_id'], unique=True)
        batch_op.create_foreign_key('fk_posting_preferences_linkedin_account_id', 'linkedin_accounts', ['linkedin_account_id'], ['id'])
        batch_op.create_check_constraint('ck_posting_preference_one_target', '(meta_page_id IS NOT NULL AND linkedin_account_id IS NULL) OR (meta_page_id IS NULL AND linkedin_account_id IS NOT NULL)')

    with op.batch_alter_table('scheduled_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.Enum('FACEBOOK', 'INSTAGRAM', 'LINKEDIN', name='scheduledplatform'), server_default='FACEBOOK', nullable=False))
        batch_op.add_column(sa.Column('linkedin_account_id', sa.Integer(), nullable=True))
        batch_op.alter_column('meta_page_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_scheduled_posts_linkedin_account_id'), ['linkedin_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_posts_platform'), ['platform'], unique=False)
        batch_op.create_foreign_key('fk_scheduled_posts_linkedin_account_id', 'linkedin_accounts', ['linkedin_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scheduled_posts_linkedin_account_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_scheduled_posts_platform'))
        batch_op.drop_index(batch_op.f('ix_scheduled_posts_linkedin_account_id'))
        batch_op.alter_column('meta_page_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('linkedin_account_id')
        batch_op.drop_column('platform')

    with op.batch_alter_table('posting_preferences', schema=None) as batch_op:
        batch_op.drop_constraint('ck_posting_preference_one_target', type_='check')
        batch_op.drop_constraint('fk_posting_preferences_linkedin_account_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_posting_preferences_linkedin_account_id'))
        batch_op.alter_column('meta_page_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('linkedin_account_id')

    # ### end Alembic commands ###
