"""baseline schema

Revision ID: fcaf17d3b49b
Revises: 
Create Date: 2026-08-19 21:18:45.613761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcaf17d3b49b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_categories_slug'), ['slug'], unique=True)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('hook_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('default_hook', sa.String(length=512), nullable=True),
    sa.Column('default_cta', sa.String(length=256), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['content_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hook_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hook_templates_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hook_templates_id'), ['id'], unique=False)

    op.create_table('linkedin_user_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('linkedin_user_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('linkedin_user_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_linkedin_user_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_linkedin_user_tokens_linkedin_user_id'), ['linkedin_user_id'], unique=False)

    op.create_table('meta_user_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('meta_user_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('meta_user_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meta_user_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_user_tokens_meta_user_id'), ['meta_user_id'], unique=False)

    op.create_table('oauth_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_states_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_states_state'), ['state'], unique=True)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PRO', 'AGENCY', name='subscriptiontier'), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('content_generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=200), nullable=True),
    sa.Column('extra_instruction', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'SUCCEEDED', 'VALIDATION_FAILED', 'FAILED', name='generationstatus'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('hook', sa.String(length=500), nullable=True),
    sa.Column('call_to_action', sa.String(length=500), nullable=True),
    sa.Column('hashtags_json', sa.Text(), nullable=True),
    sa.Column('risk_flags_json', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['content_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_generation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_generation_jobs_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_generation_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_generation_jobs_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_content_generation_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_generation_jobs_requested_by_id'), ['requested_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_generation_jobs_status'), ['status'], unique=False)

    op.create_table('content_generation_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=200), nullable=True),
    sa.Column('extra_instruction', sa.Text(), nullable=True),
    sa.Column('recurrence', sa.Enum('DAILY', 'WEEKLY', name='generationrecurrence'), nullable=False),
    sa.Column('approval_mode', sa.Enum('REQUIRED', 'CONTROLLED', name='approvalmode'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', name='generationplanstatus'), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['content_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_generation_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_generation_plans_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_generation_plans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_generation_plans_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_generation_plans_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_generation_plans_status'), ['status'], unique=False)

    op.create_table('linkedin_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('linkedin_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('account_type', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'linkedin_id', name='uq_linkedin_accounts_user_id')
    )
    with op.batch_alter_table('linkedin_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_linkedin_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_linkedin_accounts_linkedin_id'), ['linkedin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_linkedin_accounts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_linkedin_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_user_id'), ['user_id'], unique=False)

    op.create_table('meta_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=64), nullable=False),
    sa.Column('page_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'page_id', name='uq_meta_pages_user_page')
    )
    with op.batch_alter_table('meta_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meta_pages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_pages_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_pages_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_pages_user_id'), ['user_id'], unique=False)

    op.create_table('organization_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'EDITOR', name='organizationrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_user')
    )
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_members_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_user_id'), ['user_id'], unique=False)

    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='contentstatus'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schedule_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schedule_meta_page_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('generated_by_ai', sa.Boolean(), nullable=False),
    sa.Column('generation_job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['generation_job_id'], ['content_generation_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_meta_page_id'], ['meta_pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_generated_by_ai'), ['generated_by_ai'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_generation_job_id'), ['generation_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_media_id'), ['media_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_schedule_meta_page_id'), ['schedule_meta_page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_title'), ['title'], unique=False)

    op.create_table('content_generation_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_job_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_token_count', sa.Integer(), nullable=False),
    sa.Column('candidates_token_count', sa.Integer(), nullable=False),
    sa.Column('thoughts_token_count', sa.Integer(), nullable=False),
    sa.Column('cached_content_token_count', sa.Integer(), nullable=False),
    sa.Column('total_token_count', sa.Integer(), nullable=False),
    sa.Column('input_cost_per_million_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('output_cost_per_million_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=14, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['generation_job_id'], ['content_generation_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_generation_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_generation_usage_generation_job_id'), ['generation_job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_content_generation_usage_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_generation_usage_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_generation_usage_requested_by_id'), ['requested_by_id'], unique=False)

    op.create_table('posting_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_page_id', sa.Integer(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('max_posts_per_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meta_page_id'], ['meta_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posting_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posting_preferences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posting_preferences_meta_page_id'), ['meta_page_id'], unique=True)

    op.create_table('content_publish_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('meta_page_id', sa.Integer(), nullable=True),
    sa.Column('linkedin_account_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'POSTED', 'FAILED', name='publishstatusenum'), nullable=False),
    sa.Column('platform_post_id', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linkedin_account_id'], ['linkedin_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meta_page_id'], ['meta_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_publish_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_publish_status_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_publish_status_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_publish_status_linkedin_account_id'), ['linkedin_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_publish_status_meta_page_id'), ['meta_page_id'], unique=False)

    op.create_table('scheduled_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('meta_page_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'POSTED', 'CANCELLED', 'FAILED', 'RETRYING', 'PARTIALLY_FAILED', 'DEAD_LETTER', name='scheduledpoststatus'), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=512), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['meta_page_id'], ['meta_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_posts_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_posts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_posts_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_scheduled_posts_meta_page_id'), ['meta_page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_posts_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_posts_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_posts_status'))
        batch_op.drop_index(batch_op.f('ix_scheduled_posts_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_scheduled_posts_meta_page_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_posts_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_scheduled_posts_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_posts_content_id'))

    op.drop_table('scheduled_posts')
    with op.batch_alter_table('content_publish_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_publish_status_meta_page_id'))
        batch_op.drop_index(batch_op.f('ix_content_publish_status_linkedin_account_id'))
        batch_op.drop_index(batch_op.f('ix_content_publish_status_id'))
        batch_op.drop_index(batch_op.f('ix_content_publish_status_content_id'))

    op.drop_table('content_publish_status')
    with op.batch_alter_table('posting_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posting_preferences_meta_page_id'))
        batch_op.drop_index(batch_op.f('ix_posting_preferences_id'))

    op.drop_table('posting_preferences')
    with op.batch_alter_table('content_generation_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_generation_usage_requested_by_id'))
        batch_op.drop_index(batch_op.f('ix_content_generation_usage_organization_id'))
        batch_op.drop_index(batch_op.f('ix_content_generation_usage_id'))
        batch_op.drop_index(batch_op.f('ix_content_generation_usage_generation_job_id'))

    op.drop_table('content_generation_usage')
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_title'))
        batch_op.drop_index(batch_op.f('ix_content_status'))
        batch_op.drop_index(batch_op.f('ix_content_schedule_meta_page_id'))
        batch_op.drop_index(batch_op.f('ix_content_organization_id'))
        batch_op.drop_index(batch_op.f('ix_content_media_id'))
        batch_op.drop_index(batch_op.f('ix_content_id'))
        batch_op.drop_index(batch_op.f('ix_content_generation_job_id'))
        batch_op.drop_index(batch_op.f('ix_content_generated_by_ai'))

    op.drop_table('content')
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_organization_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_id'))

    op.drop_table('organization_members')
    with op.batch_alter_table('meta_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meta_pages_user_id'))
        batch_op.drop_index(batch_op.f('ix_meta_pages_page_id'))
        batch_op.drop_index(batch_op.f('ix_meta_pages_organization_id'))
        batch_op.drop_index(batch_op.f('ix_meta_pages_id'))

    op.drop_table('meta_pages')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_user_id'))
        batch_op.drop_index(batch_op.f('ix_media_organization_id'))
        batch_op.drop_index(batch_op.f('ix_media_id'))

    op.drop_table('media')
    with op.batch_alter_table('linkedin_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_linkedin_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_linkedin_accounts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_linkedin_accounts_linkedin_id'))
        batch_op.drop_index(batch_op.f('ix_linkedin_accounts_id'))

    op.drop_table('linkedin_accounts')
    with op.batch_alter_table('content_generation_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_generation_plans_status'))
        batch_op.drop_index(batch_op.f('ix_content_generation_plans_organization_id'))
        batch_op.drop_index(batch_op.f('ix_content_generation_plans_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_content_generation_plans_id'))
        batch_op.drop_index(batch_op.f('ix_content_generation_plans_created_by_id'))

    op.drop_table('content_generation_plans')
    with op.batch_alter_table('content_generation_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_generation_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_content_generation_jobs_requested_by_id'))
        batch_op.drop_index(batch_op.f('ix_content_generation_jobs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_content_generation_jobs_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_content_generation_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_content_generation_jobs_category_id'))

    op.drop_table('content_generation_jobs')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_id'))

    op.drop_table('organizations')
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_states_state'))
        batch_op.drop_index(batch_op.f('ix_oauth_states_id'))

    op.drop_table('oauth_states')
    with op.batch_alter_table('meta_user_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meta_user_tokens_meta_user_id'))
        batch_op.drop_index(batch_op.f('ix_meta_user_tokens_id'))

    op.drop_table('meta_user_tokens')
    with op.batch_alter_table('linkedin_user_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_linkedin_user_tokens_linkedin_user_id'))
        batch_op.drop_index(batch_op.f('ix_linkedin_user_tokens_id'))

    op.drop_table('linkedin_user_tokens')
    with op.batch_alter_table('hook_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hook_templates_id'))
        batch_op.drop_index(batch_op.f('ix_hook_templates_category_id'))

    op.drop_table('hook_templates')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))
        batch_op.drop_index(batch_op.f('ix_system_settings_id'))

    op.drop_table('system_settings')
    with op.batch_alter_table('content_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_content_categories_id'))

    op.drop_table('content_categories')
    # ### end Alembic commands ###
