export type TemplateFamily =
  | 'fashion-editorial'
  | 'service-editorial'
  | 'product-catalog'
  | 'technology-explainer'
  | 'quote-card'
  | 'collection-story';

export type CardLayout = 'split' | 'hero' | 'steps' | 'grid' | 'quote' | 'proof' | 'diagram';

export interface VisualCardDefinition {
  id: string;
  version: number;
  name: string;
  family: TemplateFamily;
  categorySlugs: string[];
  objectiveValues: string[];
  description: string;
  bestFor: string;
  layout: CardLayout;
  heroLabel: string;
  slots: string[];
  requiredAssets: string[];
  optionalAssets: string[];
  imageTextBudget: [number, number];
  ctaExamples: string[];
  preview: {
    background: string;
    accent: string;
    panel: string;
    text: string;
    muted: string;
    visual: string;
  };
}

const IT = [
  'it-products-technology-solutions', 'software-products-saas', 'business-software-erp-crm',
  'custom-software-development', 'website-development', 'ecommerce-development',
  'mobile-app-development', 'ui-ux-product-design', 'cloud-infrastructure', 'devops-deployment',
  'cybersecurity', 'managed-it-support', 'data-ai-automation', 'api-integrations',
  'quality-assurance-testing', 'it-consulting-digital-transformation', 'hosting-domain-maintenance',
  'hardware-network-solutions', 'technical-training-enablement',
];
const FASHION = ['product-showcase', 'collection-launch', 'bridal-occasion', 'styling-tips', 'fabric-craft', 'customer-story', 'offer-booking', 'fashion-quote'];
const EDUCATION = ['educational-howto', 'technical-training-enablement'];
const QUOTES = ['love-quotes', 'truth-quotes', 'motivational-quotes', 'pain-quotes', 'fashion-quote'];
const SERVICE = ['service-showcase', 'offer-booking', 'it-consulting-digital-transformation', 'managed-it-support', 'hosting-domain-maintenance', 'hardware-network-solutions', ...IT];
const PRODUCT = ['product-showcase', 'software-products-saas', 'business-software-erp-crm', 'product-showcase'];
const PROOF = ['case-study-results', 'client-story', 'customer-story'];
const INSIGHTS = ['industry-insights', 'educational-howto', 'data-ai-automation', 'technical-training-enablement'];

const card = (
  value: Omit<VisualCardDefinition, 'version'>,
): VisualCardDefinition => ({ version: 1, ...value });

export const TEMPLATE_CATALOG: VisualCardDefinition[] = [
  card({ id: 'it-feature-spotlight', name: 'Feature spotlight', family: 'product-catalog', categorySlugs: IT, objectiveValues: ['awareness', 'product discovery', 'conversion', 'lead generation'], description: 'Product or interface image with one verified capability and a focused action.', bestFor: 'Software features, SaaS, ERP/CRM, apps, and digital products', layout: 'split', heroLabel: 'PRODUCT / UI', slots: ['logo', 'screenshot or product image', 'eyebrow', 'headline', 'one benefit', 'CTA', 'website/handle'], requiredAssets: ['workspace screenshot or product image'], optionalAssets: ['feature icon', 'verified integration mark'], imageTextBudget: [48, 60], ctaExamples: ['Request demo', 'Explore product'], preview: { background: '#0f172a', accent: '#38bdf8', panel: '#172554', text: '#f8fafc', muted: '#bae6fd', visual: '#38bdf8' } }),
  card({ id: 'it-workflow-explainer', name: 'Workflow in three steps', family: 'technology-explainer', categorySlugs: IT, objectiveValues: ['education', 'awareness', 'lead generation'], description: 'A numbered workflow that makes a technical process easy to scan.', bestFor: 'Implementation, onboarding, automation, and service processes', layout: 'steps', heroLabel: 'HOW IT WORKS', slots: ['logo', 'headline', 'step 1', 'step 2', 'step 3', 'CTA', 'footer'], requiredAssets: ['verified workflow facts'], optionalAssets: ['screenshot', 'step icons'], imageTextBudget: [52, 68], ctaExamples: ['See how it works', 'Talk to an expert'], preview: { background: '#07111f', accent: '#22d3ee', panel: '#12304a', text: '#ecfeff', muted: '#a5f3fc', visual: '#22d3ee' } }),
  card({ id: 'it-integration-map', name: 'Integration map', family: 'technology-explainer', categorySlugs: ['api-integrations', 'software-products-saas', 'business-software-erp-crm'], objectiveValues: ['education', 'product discovery', 'lead generation'], description: 'A central system connected to verified tools, APIs, or business workflows.', bestFor: 'APIs, webhooks, ERP/CRM, and systems integration', layout: 'diagram', heroLabel: 'INTEGRATIONS', slots: ['logo', 'headline', 'central system', '2–4 connected systems', 'CTA', 'footer'], requiredAssets: ['verified integration names'], optionalAssets: ['approved partner logos'], imageTextBudget: [52, 68], ctaExamples: ['Discuss integration', 'Explore the workflow'], preview: { background: '#111827', accent: '#a78bfa', panel: '#312e81', text: '#f5f3ff', muted: '#ddd6fe', visual: '#c4b5fd' } }),
  card({ id: 'it-security-checklist', name: 'Security checklist', family: 'technology-explainer', categorySlugs: ['cybersecurity', 'managed-it-support', 'cloud-infrastructure'], objectiveValues: ['education', 'awareness', 'lead generation'], description: 'A high-contrast checklist for verified security or operational controls.', bestFor: 'Cybersecurity, support, compliance preparation, and risk education', layout: 'grid', heroLabel: 'SECURITY / SUPPORT', slots: ['logo', 'headline', '3 checks', 'evidence label', 'CTA', 'footer'], requiredAssets: ['verified control facts'], optionalAssets: ['shield icon', 'source label'], imageTextBudget: [52, 68], ctaExamples: ['Review your setup', 'Talk to security'], preview: { background: '#0b1220', accent: '#4ade80', panel: '#14532d', text: '#f0fdf4', muted: '#bbf7d0', visual: '#86efac' } }),
  card({ id: 'it-cloud-architecture', name: 'Cloud architecture', family: 'technology-explainer', categorySlugs: ['cloud-infrastructure', 'devops-deployment', 'hosting-domain-maintenance'], objectiveValues: ['education', 'awareness', 'lead generation'], description: 'A simplified input-to-service-to-output architecture diagram.', bestFor: 'Cloud, hosting, DevOps, deployment, and infrastructure', layout: 'diagram', heroLabel: 'CLOUD / INFRASTRUCTURE', slots: ['logo', 'headline', 'architecture nodes', 'verified labels', 'CTA', 'footer'], requiredAssets: ['verified architecture facts'], optionalAssets: ['provider mark when used'], imageTextBudget: [52, 68], ctaExamples: ['Plan your setup', 'Discuss infrastructure'], preview: { background: '#082f49', accent: '#67e8f9', panel: '#164e63', text: '#ecfeff', muted: '#a5f3fc', visual: '#22d3ee' } }),
  card({ id: 'it-ui-tour', name: 'Product UI tour', family: 'product-catalog', categorySlugs: ['software-products-saas', 'business-software-erp-crm', 'ui-ux-product-design', 'mobile-app-development'], objectiveValues: ['product discovery', 'awareness', 'conversion'], description: 'A device or browser mockup with two concise callouts.', bestFor: 'Apps, SaaS dashboards, portals, and UI/UX work', layout: 'hero', heroLabel: 'PRODUCT TOUR', slots: ['logo', 'UI screenshot', 'headline', 'callout 1', 'callout 2', 'CTA'], requiredAssets: ['workspace UI screenshot'], optionalAssets: ['device frame'], imageTextBudget: [48, 60], ctaExamples: ['Explore the product', 'Book a walkthrough'], preview: { background: '#172554', accent: '#fbbf24', panel: '#1e3a8a', text: '#eff6ff', muted: '#bfdbfe', visual: '#fef3c7' } }),
  card({ id: 'it-qa-testing', name: 'QA and testing', family: 'technology-explainer', categorySlugs: ['quality-assurance-testing', 'custom-software-development', 'website-development', 'mobile-app-development'], objectiveValues: ['education', 'awareness', 'lead generation'], description: 'A test matrix and device/browser cue for quality assurance content.', bestFor: 'QA, testing, launches, and reliability education', layout: 'grid', heroLabel: 'QUALITY CHECK', slots: ['logo', 'headline', '3 test checks', 'device/browser cue', 'CTA'], requiredAssets: ['verified testing facts'], optionalAssets: ['product screenshot'], imageTextBudget: [52, 68], ctaExamples: ['Get a QA review', 'Plan your testing'], preview: { background: '#18181b', accent: '#f472b6', panel: '#3f3f46', text: '#fff1f2', muted: '#fecdd3', visual: '#f9a8d4' } }),
  card({ id: 'it-training-enablement', name: 'Technical training', family: 'technology-explainer', categorySlugs: [...new Set([...EDUCATION, ...IT])], objectiveValues: ['education', 'awareness', 'lead generation'], description: 'A lesson or workshop card with audience and topic clarity.', bestFor: 'Technical training, enablement, workshops, and certifications', layout: 'steps', heroLabel: 'LEARN / ENABLE', slots: ['logo', 'instructor or topic visual', 'headline', 'audience', '3 topics', 'CTA'], requiredAssets: ['verified training/topic details'], optionalAssets: ['instructor image'], imageTextBudget: [52, 68], ctaExamples: ['View training', 'Join the workshop'], preview: { background: '#312e81', accent: '#f0abfc', panel: '#4c1d95', text: '#faf5ff', muted: '#f5d0fe', visual: '#f0abfc' } }),
  card({ id: 'fashion-product-hero', name: 'Product hero', family: 'fashion-editorial', categorySlugs: FASHION, objectiveValues: ['awareness', 'product discovery', 'conversion'], description: 'A garment or model image remains the focal point with restrained editorial type.', bestFor: 'Suits, garments, fabrics, boutique products, and custom designs', layout: 'hero', heroLabel: 'NEW / FEATURED', slots: ['logo', 'product/model image', 'collection label', 'headline', 'descriptor', 'CTA', 'handle'], requiredAssets: ['approved product or model image'], optionalAssets: ['fabric detail', 'price when supplied'], imageTextBudget: [48, 60], ctaExamples: ['View the collection', 'Enquire now'], preview: { background: '#291b1f', accent: '#f5d0c5', panel: '#5b3037', text: '#fff7ed', muted: '#fed7aa', visual: '#fda4af' } }),
  card({ id: 'fashion-lookbook', name: 'Lookbook pair', family: 'collection-story', categorySlugs: ['collection-launch', 'product-showcase', 'styling-tips'], objectiveValues: ['awareness', 'product discovery'], description: 'Two or three coordinated editorial images tell a collection story.', bestFor: 'Seasonal launches, outfit inspiration, and lookbooks', layout: 'grid', heroLabel: 'LOOKBOOK', slots: ['logo', '2–3 editorial images', 'collection name', 'occasion/season label', 'CTA'], requiredAssets: ['approved campaign/product images'], optionalAssets: ['collection palette'], imageTextBudget: [52, 68], ctaExamples: ['View collection', 'Save the look'], preview: { background: '#1c1917', accent: '#f59e0b', panel: '#44403c', text: '#fffbeb', muted: '#fde68a', visual: '#fcd34d' } }),
  card({ id: 'fashion-style-guide', name: 'Styling guide', family: 'fashion-editorial', categorySlugs: ['styling-tips', 'product-showcase', 'bridal-occasion'], objectiveValues: ['education', 'awareness', 'product discovery'], description: 'A hero outfit with two or three practical styling callouts.', bestFor: 'Color, fit, accessories, and occasion styling', layout: 'grid', heroLabel: 'STYLE GUIDE', slots: ['logo', 'outfit image', 'headline', '2–3 styling tips', 'CTA'], requiredAssets: ['approved product or outfit image'], optionalAssets: ['accessory detail images'], imageTextBudget: [48, 60], ctaExamples: ['Ask a stylist', 'Save this look'], preview: { background: '#faf7f2', accent: '#be123c', panel: '#ffe4e6', text: '#4c0519', muted: '#9f1239', visual: '#fb7185' } }),
  card({ id: 'fashion-craft', name: 'Craft and fabric detail', family: 'fashion-editorial', categorySlugs: ['fabric-craft', 'product-showcase'], objectiveValues: ['education', 'awareness', 'product discovery'], description: 'A macro material image with verified craftsmanship callouts.', bestFor: 'Tailoring, embroidery, fabric quality, and making stories', layout: 'split', heroLabel: 'CRAFT / DETAIL', slots: ['logo', 'macro fabric image', 'material label', 'headline', '2 facts', 'CTA'], requiredAssets: ['approved fabric/craft image', 'verified material facts'], optionalAssets: ['process image'], imageTextBudget: [48, 60], ctaExamples: ['Discover the craft', 'Ask about the fabric'], preview: { background: '#292524', accent: '#d6d3d1', panel: '#57534e', text: '#fafaf9', muted: '#e7e5e4', visual: '#d6d3d1' } }),
  card({ id: 'fashion-bridal', name: 'Bridal and occasion edit', family: 'fashion-editorial', categorySlugs: ['bridal-occasion', 'offer-booking'], objectiveValues: ['awareness', 'product discovery', 'conversion'], description: 'An occasion-led hero image with a clear appointment or inquiry panel.', bestFor: 'Bridal, partywear, ceremony, and custom-order intent', layout: 'hero', heroLabel: 'BRIDAL / OCCASION', slots: ['logo', 'occasion image', 'headline', 'occasion label', 'appointment detail', 'CTA'], requiredAssets: ['approved occasion image'], optionalAssets: ['appointment/contact detail'], imageTextBudget: [48, 60], ctaExamples: ['Book appointment', 'Enquire for your occasion'], preview: { background: '#3b0764', accent: '#f5d0fe', panel: '#701a75', text: '#fdf4ff', muted: '#f5d0fe', visual: '#e879f9' } }),
  card({ id: 'fashion-ugc-proof', name: 'Customer styling proof', family: 'collection-story', categorySlugs: ['customer-story', 'product-showcase'], objectiveValues: ['proof', 'community', 'product discovery'], description: 'Permissioned customer content or a verified quote with visible provenance.', bestFor: 'UGC, customer stories, and real-world styling', layout: 'proof', heroLabel: 'CUSTOMER STORY', slots: ['logo', 'permissioned customer image', 'short quote', 'handle/name if approved', 'CTA'], requiredAssets: ['permissioned UGC or approved testimonial'], optionalAssets: ['product detail'], imageTextBudget: [52, 68], ctaExamples: ['Share your look', 'See the story'], preview: { background: '#0f172a', accent: '#fb7185', panel: '#3f1d2e', text: '#fff1f2', muted: '#fecdd3', visual: '#fb7185' } }),
  card({ id: 'service-problem-solution', name: 'Problem to solution', family: 'service-editorial', categorySlugs: SERVICE, objectiveValues: ['awareness', 'lead generation', 'conversion'], description: 'A concrete problem state connected to one verified service solution.', bestFor: 'Consulting, agencies, local services, and managed support', layout: 'split', heroLabel: 'PROBLEM → SOLUTION', slots: ['logo', 'service image/illustration', 'problem headline', 'solution benefit', 'CTA', 'footer'], requiredAssets: ['verified service capability'], optionalAssets: ['workspace/team image'], imageTextBudget: [48, 60], ctaExamples: ['Book consultation', 'Start a conversation'], preview: { background: '#0c4a6e', accent: '#fbbf24', panel: '#164e63', text: '#f0f9ff', muted: '#bae6fd', visual: '#fde68a' } }),
  card({ id: 'service-capability-grid', name: 'Capability grid', family: 'service-editorial', categorySlugs: SERVICE, objectiveValues: ['awareness', 'lead generation', 'product discovery'], description: 'One service promise supported by three concise capability chips.', bestFor: 'Professional services, agencies, IT services, and local businesses', layout: 'grid', heroLabel: 'CAPABILITIES', slots: ['logo', 'service image', 'headline', '3 capabilities', 'CTA', 'footer'], requiredAssets: ['verified service list'], optionalAssets: ['team/process image'], imageTextBudget: [48, 60], ctaExamples: ['Explore services', 'Talk to our team'], preview: { background: '#172554', accent: '#60a5fa', panel: '#1e40af', text: '#eff6ff', muted: '#bfdbfe', visual: '#93c5fd' } }),
  card({ id: 'service-process', name: 'How we work', family: 'collection-story', categorySlugs: SERVICE, objectiveValues: ['education', 'awareness', 'lead generation'], description: 'A three-step process timeline that makes an intangible service concrete.', bestFor: 'Consulting, implementation, onboarding, and project services', layout: 'steps', heroLabel: 'OUR PROCESS', slots: ['logo', 'team/process image', 'headline', 'step 1–3', 'CTA', 'footer'], requiredAssets: ['verified process facts'], optionalAssets: ['team image'], imageTextBudget: [52, 68], ctaExamples: ['Start a conversation', 'See our process'], preview: { background: '#134e4a', accent: '#5eead4', panel: '#115e59', text: '#f0fdfa', muted: '#99f6e4', visual: '#5eead4' } }),
  card({ id: 'service-local-offer', name: 'Local offer', family: 'service-editorial', categorySlugs: SERVICE, objectiveValues: ['conversion', 'awareness', 'lead generation'], description: 'A configured local service or consultation offer with exact terms and a safe CTA band.', bestFor: 'Local businesses, consultation bookings, and verified promotions', layout: 'hero', heroLabel: 'LOCAL / OFFER', slots: ['logo', 'service image', 'offer headline', 'exact terms', 'location', 'CTA', 'footer'], requiredAssets: ['verified offer or service facts'], optionalAssets: ['location and expiry when configured'], imageTextBudget: [48, 60], ctaExamples: ['Book consultation', 'Enquire now'], preview: { background: '#431407', accent: '#fdba74', panel: '#9a3412', text: '#fff7ed', muted: '#fed7aa', visual: '#fb923c' } }),
  card({ id: 'service-faq', name: 'FAQ answer', family: 'service-editorial', categorySlugs: SERVICE, objectiveValues: ['education', 'awareness', 'lead generation'], description: 'One verified customer question and a concise answer with supportive visual context.', bestFor: 'Service explanations, support, consulting, and trust-building', layout: 'split', heroLabel: 'FAQ', slots: ['logo', 'service image/icon', 'question', 'short answer', 'CTA', 'footer'], requiredAssets: ['verified answer or workspace source'], optionalAssets: ['supporting image/icon'], imageTextBudget: [48, 60], ctaExamples: ['Ask us', 'Learn more'], preview: { background: '#042f2e', accent: '#2dd4bf', panel: '#115e59', text: '#f0fdfa', muted: '#99f6e4', visual: '#5eead4' } }),
  card({ id: 'service-testimonial', name: 'Client voice', family: 'collection-story', categorySlugs: PROOF, objectiveValues: ['proof', 'awareness', 'lead generation'], description: 'A verified client quote or outcome with clear identity and provenance state.', bestFor: 'Client stories, testimonials, and service credibility', layout: 'proof', heroLabel: 'CLIENT STORY', slots: ['logo', 'client/service image', 'short quote', 'client identity state', 'CTA'], requiredAssets: ['approved testimonial or case evidence'], optionalAssets: ['client logo when approved'], imageTextBudget: [52, 68], ctaExamples: ['See how we helped', 'Read the case'], preview: { background: '#111827', accent: '#f59e0b', panel: '#3f2a0a', text: '#fffbeb', muted: '#fde68a', visual: '#fbbf24' } }),
  card({ id: 'product-benefit-stack', name: 'Benefit stack', family: 'product-catalog', categorySlugs: PRODUCT, objectiveValues: ['product discovery', 'awareness', 'conversion'], description: 'A product image with three verified benefit rows and a clear action.', bestFor: 'Retail, e-commerce, software products, and catalog content', layout: 'grid', heroLabel: 'PRODUCT BENEFITS', slots: ['logo', 'product image', 'headline', '3 benefits', 'CTA', 'footer'], requiredAssets: ['approved product image', 'verified benefit facts'], optionalAssets: ['price when supplied'], imageTextBudget: [48, 60], ctaExamples: ['View product', 'Learn more'], preview: { background: '#1f2937', accent: '#f97316', panel: '#7c2d12', text: '#fff7ed', muted: '#fed7aa', visual: '#fdba74' } }),
  card({ id: 'product-comparison', name: 'Product comparison', family: 'collection-story', categorySlugs: PRODUCT, objectiveValues: ['product discovery', 'conversion'], description: 'Aligned product variants with verified attributes and no unsupported superlatives.', bestFor: 'Plans, packages, variants, and product selection', layout: 'grid', heroLabel: 'COMPARE OPTIONS', slots: ['logo', '2–3 product images', 'comparison labels', 'verified attributes', 'CTA'], requiredAssets: ['approved product images and attributes'], optionalAssets: ['price/availability when supplied'], imageTextBudget: [52, 68], ctaExamples: ['Compare options', 'Find your fit'], preview: { background: '#f8fafc', accent: '#4f46e5', panel: '#e0e7ff', text: '#1e1b4b', muted: '#4338ca', visual: '#818cf8' } }),
  card({ id: 'product-offer', name: 'Offer card', family: 'product-catalog', categorySlugs: ['offer-booking', 'product-showcase'], objectiveValues: ['conversion', 'product discovery'], description: 'A product or service with exact offer terms and a separate CTA-safe band.', bestFor: 'Configured promotions, consultations, launches, and bookings', layout: 'hero', heroLabel: 'LIMITED / OFFER', slots: ['logo', 'product/service image', 'offer headline', 'exact terms', 'expiry when configured', 'CTA', 'terms footer'], requiredAssets: ['verified offer facts and image'], optionalAssets: ['expiry/date when configured'], imageTextBudget: [48, 60], ctaExamples: ['Claim offer', 'Book now'], preview: { background: '#450a0a', accent: '#fca5a5', panel: '#991b1b', text: '#fff1f2', muted: '#fecaca', visual: '#f87171' } }),
  card({ id: 'case-study-result', name: 'Case result', family: 'collection-story', categorySlugs: PROOF, objectiveValues: ['proof', 'awareness', 'lead generation'], description: 'Challenge, solution, and one sourced result in a compact evidence-led composition.', bestFor: 'IT projects, agencies, marketing, consulting, and customer proof', layout: 'proof', heroLabel: 'CASE STUDY', slots: ['logo', 'project/client visual', 'challenge label', 'solution label', 'one verified result', 'source label', 'CTA'], requiredAssets: ['approved case-study evidence'], optionalAssets: ['client logo', 'chart/screenshot'], imageTextBudget: [52, 68], ctaExamples: ['Read the case', 'See the result'], preview: { background: '#0f172a', accent: '#4ade80', panel: '#14532d', text: '#f0fdf4', muted: '#bbf7d0', visual: '#86efac' } }),
  card({ id: 'education-quick-tip', name: 'One quick tip', family: 'technology-explainer', categorySlugs: EDUCATION, objectiveValues: ['education', 'awareness', 'community'], description: 'One lesson, one useful action, and one supportive visual.', bestFor: 'Education, coaching, technical learning, and practical tips', layout: 'split', heroLabel: 'QUICK TIP', slots: ['logo', 'topic illustration/photo', 'number', 'headline', 'action line', 'CTA'], requiredAssets: ['verified educational point'], optionalAssets: ['instructor/topic image'], imageTextBudget: [52, 68], ctaExamples: ['Save this tip', 'Learn more'], preview: { background: '#0f766e', accent: '#fde047', panel: '#115e59', text: '#f0fdfa', muted: '#ccfbf1', visual: '#fde047' } }),
  card({ id: 'education-checklist', name: 'Learning checklist', family: 'technology-explainer', categorySlugs: EDUCATION, objectiveValues: ['education', 'awareness'], description: 'A scannable three-to-five item checklist for a defined learner.', bestFor: 'How-to posts, study tips, enablement, and guides', layout: 'grid', heroLabel: 'CHECKLIST', slots: ['logo', 'topic visual', 'headline', '3–5 checklist items', 'CTA'], requiredAssets: ['verified checklist items'], optionalAssets: ['illustration'], imageTextBudget: [52, 68], ctaExamples: ['Save the checklist', 'Get the full guide'], preview: { background: '#1e3a8a', accent: '#facc15', panel: '#1d4ed8', text: '#eff6ff', muted: '#bfdbfe', visual: '#fde047' } }),
  card({ id: 'education-course', name: 'Course or workshop', family: 'service-editorial', categorySlugs: EDUCATION, objectiveValues: ['awareness', 'conversion', 'lead generation'], description: 'Instructor or topic visual plus audience and configured event/course details.', bestFor: 'Courses, classes, workshops, webinars, and training', layout: 'hero', heroLabel: 'COURSE / WORKSHOP', slots: ['logo', 'instructor/topic image', 'course title', 'audience', 'date/time if supplied', 'CTA'], requiredAssets: ['verified course details'], optionalAssets: ['approved instructor image'], imageTextBudget: [48, 60], ctaExamples: ['View training', 'Register'], preview: { background: '#4c1d95', accent: '#f0abfc', panel: '#6b21a8', text: '#fdf4ff', muted: '#f5d0fe', visual: '#e879f9' } }),
  card({ id: 'insight-stat', name: 'One-stat insight', family: 'technology-explainer', categorySlugs: INSIGHTS, objectiveValues: ['education', 'awareness', 'lead generation'], description: 'One sourced statistic with interpretation, source/date, and a simple data visual.', bestFor: 'Industry insights, research, analytics, and data/AI', layout: 'proof', heroLabel: 'INSIGHT', slots: ['logo', 'large statistic', 'interpretation', 'source/date', 'CTA'], requiredAssets: ['verified metric and source'], optionalAssets: ['chart/illustration'], imageTextBudget: [52, 68], ctaExamples: ['Read the insight', 'Explore the data'], preview: { background: '#172554', accent: '#f472b6', panel: '#312e81', text: '#fdf2f8', muted: '#fbcfe8', visual: '#f9a8d4' } }),
  card({ id: 'insight-trend', name: 'Trend snapshot', family: 'technology-explainer', categorySlugs: INSIGHTS, objectiveValues: ['education', 'awareness'], description: 'A sourced trend with three signal chips or a mini-chart.', bestFor: 'Research, news summaries, market trends, and thought leadership', layout: 'diagram', heroLabel: 'TREND SNAPSHOT', slots: ['logo', 'trend headline', '3 signal chips', 'source/date', 'CTA'], requiredAssets: ['verified trend source'], optionalAssets: ['chart/approved image'], imageTextBudget: [52, 68], ctaExamples: ['Explore the trend', 'Read more'], preview: { background: '#022c22', accent: '#34d399', panel: '#065f46', text: '#ecfdf5', muted: '#a7f3d0', visual: '#6ee7b7' } }),
  card({ id: 'quote-editorial', name: 'Editorial quote', family: 'quote-card', categorySlugs: QUOTES, objectiveValues: ['community', 'awareness'], description: 'The quote is the focal point, supported by attribution state, brand identity, and whitespace.', bestFor: 'Love, truth, motivation, pain/healing, and fashion quotes', layout: 'quote', heroLabel: 'QUOTE', slots: ['logo/handle', 'quotation mark', 'quote', 'attribution if verified', 'CTA', 'footer'], requiredAssets: ['quote copy'], optionalAssets: ['approved portrait/background'], imageTextBudget: [80, 140], ctaExamples: ['Share if it resonates', 'Save this thought'], preview: { background: '#4a044e', accent: '#f9a8d4', panel: '#831843', text: '#fff1f2', muted: '#fbcfe8', visual: '#f9a8d4' } }),
  card({ id: 'quote-photo-overlay', name: 'Photo quote', family: 'quote-card', categorySlugs: QUOTES, objectiveValues: ['community', 'awareness'], description: 'An approved photo with a controlled overlay panel and short quote.', bestFor: 'Emotional, lifestyle, and community quote series', layout: 'hero', heroLabel: 'PHOTO QUOTE', slots: ['logo/handle', 'approved photo', 'quote', 'attribution if verified', 'CTA'], requiredAssets: ['approved photo and quote copy'], optionalAssets: ['series label'], imageTextBudget: [80, 140], ctaExamples: ['Save this thought', 'Share with someone'], preview: { background: '#1c1917', accent: '#fed7aa', panel: '#78350f', text: '#fff7ed', muted: '#fed7aa', visual: '#fdba74' } }),
  card({ id: 'quote-conversation', name: 'Conversation quote', family: 'quote-card', categorySlugs: QUOTES, objectiveValues: ['community'], description: 'Two short speech panels for a relatable conversation without fabricated speakers.', bestFor: 'Hinglish quote pages and relatable community posts', layout: 'quote', heroLabel: 'DIL KI BAAT', slots: ['logo/handle', 'speaker line 1', 'speaker line 2', 'series label', 'CTA'], requiredAssets: ['original quote/conversation copy'], optionalAssets: ['illustration'], imageTextBudget: [80, 140], ctaExamples: ['Tag someone', 'Share if true'], preview: { background: '#0f172a', accent: '#fda4af', panel: '#3f1d2e', text: '#fff1f2', muted: '#fecdd3', visual: '#fb7185' } }),
  card({ id: 'quote-series', name: 'Quote series marker', family: 'quote-card', categorySlugs: QUOTES, objectiveValues: ['community', 'awareness'], description: 'A repeatable series identity with quote, handle, and optional configured episode label.', bestFor: 'Daily Hinglish quotes and recurring community series', layout: 'quote', heroLabel: 'SERIES', slots: ['series label', 'logo/handle', 'quote', 'date/episode if configured', 'CTA'], requiredAssets: ['quote copy and series identity'], optionalAssets: ['episode/date'], imageTextBudget: [80, 140], ctaExamples: ['Follow for more', 'Save this thought'], preview: { background: '#111827', accent: '#fbbf24', panel: '#78350f', text: '#fffbeb', muted: '#fde68a', visual: '#fcd34d' } }),
];

export function getTemplateCards(categorySlug?: string, objective?: string, family?: string): VisualCardDefinition[] {
  const matching = TEMPLATE_CATALOG.filter((item) => {
    const categoryMatch = !categorySlug || item.categorySlugs.includes(categorySlug);
    const objectiveMatch = !objective || item.objectiveValues.includes(objective) || objective === 'service-showcase';
    const familyMatch = !family || item.family === family;
    return categoryMatch && objectiveMatch && familyMatch;
  });
  if (matching.length > 0) return matching;
  const familyMatches = TEMPLATE_CATALOG.filter((item) => (!family || item.family === family) && (!objective || item.objectiveValues.includes(objective)));
  return familyMatches.length ? familyMatches : TEMPLATE_CATALOG.filter((item) => !family || item.family === family);
}

export function getRecommendedCard(categorySlug?: string, objective?: string, family?: string): VisualCardDefinition | undefined {
  return getTemplateCards(categorySlug, objective, family)[0];
}
